BeginningDash/urls.py
from django.conf.urls import url
from BeginningDash import views
from django.contrib.auth import views as myviews
from BeginningDash.views import GeneratePDF
from BeginningDash.views import GeneratePDF_4_code
from django.contrib.auth.models import User
from django.contrib.auth.views import (
	password_reset,
	password_reset_done, 
	password_reset_confirm,
	password_reset_complete
 )

app_name = 'BeginningDash'
urlpatterns = [
	url(r'^contact-us/', views.mycontact, name="contact"),
	url(r'^aboutus/', views.aboutus, name="aboutus"),
	url(r'^aboutfornonuser/', views.aboutfornonuser, name="aboutfornonuser"),
	url(r'^mycontact4offlineuser/', views.mycontact4offlineuser, name="mycontact4offlineuser"),
	url(r'^home/dashboard/$', views.homepage, name="home"),
	url(r'^coding/now/$', views.UCU, name="code"),
	url(r'^all/files/upload/$', views.AllFilesUploaded, name="allfiles"),
	url(r'^all/codes/upload/$', views.AllCodesUploaded, name="allcodes"),
	url(r'^media/upload/$', views.MediaUploaded, name="gallery"),
	url(r'^uploadpdf/$', GeneratePDF.as_view(),name="pdf"),
	url(r'^uploadpdf/code/$', GeneratePDF_4_code.as_view(),name="pdf_code"),
	url(r'^created_document/$', views.created_document, name='created_document'),
	url(r'^profile/$', views.view_profile, name="view_profile"),
	url(r'^user/profile/edit/$', views.edit_profile, name='edit_profile'),
	url(r'^account/logout/$', views.logout,name="logout"),
	url(r'^(?P<upload_id>[0-9]+)/delete/files$', views.upload_delete, name="delete_upload"),
	url(r'^(?P<code_id>[0-9]+)/delete/codes$', views.code_delete, name="delete_code"),
	url(r'^login-reg/', views.loginX_regX, name='loginX_regX'),	
	url(r'^register/response/', views.register_response, name='reg_response'),
	url(r'^change-password/$', views.change_password, name='change_password'),
	url(r'^reset-password/$', password_reset,
		{ "template_name":"Beginning/reset_password.html","post_reset_redirect":"BeginningDash:password_reset_done",
		"email_template_name":"Beginning/reset_password_email.html"},
		name='reset_password'),
	url(r'^reset-password/done/$', password_reset_done,{"template_name":"Beginning/reset_password_done.html"},name='password_reset_done'),
	url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', password_reset_confirm,{"post_reset_redirect":"BeginningDash:password_reset_complete","template_name":"Beginning/reset_password_confirm.html"}, name='password_reset_confirm' ),
	url(r'^reset-password/complete/$', password_reset_complete,{"template_name":"Beginning/reset_password_complete.html"},name="password_reset_complete")
]

DashNig/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from BeginningDash import urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('BeginningDash.urls', namespace="BeginningDash")),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/Additions/AllCodesUpload.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<br>
<div class="col-md-12"> 
	<table  class="table table-condensed" border='1' cellpadding='10' cellspacing='10' > 
		<tr>
			<th colspan='3'><p align="middle"><b  class="warning"><button class="btn btn-info disabled" type="button">
			<b>CODE SUMMARY</b> <span class="badge">{{total_files_4_code}}</span>
			</button></b></p></th>
		</tr>
		<tr class="warning">
			<th> DATA TYPE </th>
			<th>DATE-TIME CREATED</th>
			<th>CODES</th>
		</tr>
		<tr class="info">
			<td>File Group(ID)</td>
			<td>{% for item in item_4_code %}
				{% if item.code_creates %}
				<span class="glyphicon glyphicon-time"></span>&nbsp;{{item.code_creates}}<br>
				{% endif %}
				{% endfor %}
			</td>
			<td>{% for item in item_4_code %}
				{% if item.file_g_4_code %}
				<i class="fa fa-folder-open" aria-hidden="true"></i>&nbsp;{{item.file_g_4_code}}<br>
				{% endif %}
				{% endfor %}
			</td> 
		</tr>
             <style type="text/css">
             	.bulb{
             		color: orange;
             	}
             </style>
		<tr class="warning">
			<td>HTML</td>
			<td><i class="fa fa-lightbulb-o bulb" aria-hidden="true"></i>&nbsp;{{total_vids}}&nbsp;HTML</td>
			<td>

				{% for item in item_4_code %}
				{% if item.html %}
				<i class="fa fa-code" aria-hidden="true"></i>&nbsp;{{item.html|linebreaks|slice:"11:"}}
				{% endif %}
				{% endfor %}

			</td>
			<tr class="info">
				<td>CSS</td>
				<td><i class="fa fa-lightbulb-o bulb" aria-hidden="true"></i>&nbsp;{{total_auds}}&nbsp;CSS</td>
				<td>{% for item in item_4_code %}
					{% if item.css %}
					<i class="fa fa-code" aria-hidden="true"></i>&nbsp;{{item.css|linebreaks|slice:"11:"}}
					{% endif %}
					{% endfor %}
				</td>
			</tr> 
			<tr class="warning">     
				<td>TOTAL</td>   
				<td><i class="fa fa-file" aria-hidden="true"></i>&nbsp;{{total_total_4_code}}&nbsp;Code{{total_total_4_code|pluralize}}</td>  
				<td>
				 <i class="fa fa-folder-open" aria-hidden="true"></i>&nbsp; {{total_files}}&nbsp;Folder{{total_files_4_code|pluralize}}&nbsp;<i class="fa fa-arrows-h" aria-hidden="true"></i>&nbsp;<i class="fa fa-file" aria-hidden="true"></i>&nbsp;{{total_total_4_code}}&nbsp;Code{{total_total_4_code|pluralize}}
				</td> 
			</tr>  
		</table>
	
	<p>
	<span class="pull-left">
			<a href="javascript:history.go(-1)" onMouseOver="self.status.referrer;return true"><button type="button" class="btn btn-primary btn-xs"><i class="fa fa-angle-double-left" aria-hidden="true"></i>&nbsp;Go Back</button></a> </span>
		<span class="pull-right">
		<a href="{% url 'BeginningDash:pdf_code' %}"><button type="button" class="btn btn-primary btn-xs"><i class="fa fa-file-pdf-o" aria-hidden="true" title="DOWNLOAD SUMMARY PDF NOW"></i>&nbsp;Download Sum. PDF</button></a>
	</span>
	</p>  
	<br>
</div>
<div class="col-md-12">
	<hr>
  <div align="middle" style="background-color: #0081b5; padding: 12px;border-radius: 10px;">
	<div align="middle" style="color: whitesmoke; font-size:20px; font-weight: bold; font-family: 'satisfyregular'"><i class="fa fa-spinner fa-pulse fa-3x fa-fw" style="font-size: 19px;"></i>
	<span class="sr-only">Loading...</span>Count Down To Main Event XD [CODE]
	</div>
	 <div style="text-shadow: 1px 15px 7px rgba(0,0,0,0.5); font-size:23px; color: gold;" id="countdown" >
	   <i class="fa fa-calendar-check-o" aria-hidden="true"></i><span id="days"></span> Days 
	   <i class="fa fa-arrow-circle-right" aria-hidden="true"></i><span id="hours"> </span> Hours
	   <i class="fa fa-arrow-circle-right" aria-hidden="true"></i><span id="minutes"> </span>  Minutes
	   <i class="fa fa-arrow-circle-right" aria-hidden="true"></i><span id="seconds"> </span> Seconds 



	 </div>
	 </div>
	 <br>
	 <hr>
	 <script type="text/javascript">

      function countdown(){
        var now = new Date();
        var eventDate = new Date(2019,  00,  01, 16, 00,  00, 00)

        var currentTime = now.getTime();
        var eventTime = eventDate.getTime();
        

        var remTime = eventTime - currentTime;
        if (remTime  <= 0  )(
              $('#countdown').text('HAPPY NEW YEAR LUCKY PIUS!!!! ')
          )
        

        var s = Math.floor(remTime / 1000);
        var m = Math.floor(s / 60);
        var h = Math.floor(m / 60);
        var d = Math.floor(h / 24);

        h %= 24;
        m %= 60;
        s %= 60;

        h = (h < 10) ? "0" + h : h;
        m = (m < 10) ? "0" + m : m;
        s = (s < 10) ? "0" + s : s;

        document.getElementById("days").textContent = d;
        document.getElementById("days").innerText = d;

        document.getElementById("hours").textContent = h;
        document.getElementById("minutes").textContent = m;
        document.getElementById("seconds").textContent = s;

        setTimeout(countdown, 1000);

        
      }

      countdown();
    </script>


	
</div>


	{% endblock content %}

templates/Additions/AllFilesUpload.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<br>
<div class="col-md-12"> 
	<table  class="table table-condensed" border='1' cellpadding='10' cellspacing='10' > 
		<tr>
			<th colspan='3'><p align="middle"><b  class="warning"><button class="btn btn-info disabled" type="button">
			<b>FILE SUMMARY</b> <span class="badge">{{total_files}}</span>
			</button></b></p></th>
		</tr>
		<tr class="warning">
			<th> DATA TYPE </th>
			<th>DATE-TIME CREATED</th>
			<th>FILES</th>
		</tr>
		<tr class="info">
			<td>File Group(ID)</td>
			<td>{% for item in item %}
				{% if item.creates %}
				<span class="glyphicon glyphicon-time"></span>&nbsp;{{item.creates}}<br>
				{% endif %}
				{% endfor %}
			</td>
			<td>{% for item in item %}
				{% if item.file_g %}
				<i class="fa fa-folder-open" aria-hidden="true"></i>&nbsp;{{item.file_g}}<br>
				{% endif %}
				{% endfor %}
			</td> 
		</tr>
             <style type="text/css">
             	.bulb{
             		color: orange;
             	}
             </style>
		<tr class="warning">
			<td>VIDEOS</td>
			<td><i class="fa fa-lightbulb-o bulb" aria-hidden="true"></i>&nbsp;{{total_vids}}&nbsp;Video{{total_vids|pluralize}}</td>
			<td>

				{% for item in item %}
				{% if item.vids %}
				<span class="glyphicon glyphicon-film"></span>&nbsp;{{item.vids|linebreaks|slice:"11:"}}
				{% endif %}
				{% endfor %}

			</td>
			<tr class="info">
				<td>AUDIOS</td>
				<td><i class="fa fa-lightbulb-o bulb" aria-hidden="true"></i>&nbsp;{{total_auds}}&nbsp;Audio{{total_auds|pluralize}}</td>
				<td>{% for item in item %}
					{% if item.auds %}
					<span class="glyphicon glyphicon-headphones"></span>&nbsp;{{item.auds|linebreaks|slice:"11:"}}
					{% endif %}
					{% endfor %}
				</td>
			</tr> 
			<tr class="warning">     
				<td>IMAGES</td>   
				<td><i class="fa fa-lightbulb-o bulb" aria-hidden="true"></i>&nbsp;{{total_imgs}}&nbsp;Image{{total_imgs|pluralize}}</td>  
				<td>{% for item in item %}
					{% if item.imgs %}
					<span class="glyphicon glyphicon-picture"></span>&nbsp;{{item.imgs|linebreaks|slice:"11:"}}
					{% endif %}
					{% endfor %}
				</td> 
			</tr> 
			<tr class="warning">     
				<td>PDFS</td>   
				<td><i class="fa fa-lightbulb-o bulb" aria-hidden="true"></i>&nbsp;{{total_pdfs}}&nbsp;Pdf{{total_pdfs|pluralize}}</td>  
				<td>{% for item in item %}
					{% if item.pdfs %}
					<i class="fa fa-file-pdf-o" aria-hidden="true"></i>&nbsp;{{item.pdfs|linebreaks|slice:"11:"}}
					{% endif %}
					{% endfor %}
				</td> 
			</tr> 
			<tr class="warning">     
				<td>TOTAL</td>   
				<td><i class="fa fa-file" aria-hidden="true"></i>&nbsp;{{total_total}}&nbsp;File{{total_total|pluralize}}</td>  
				<td>
				 <i class="fa fa-folder-open" aria-hidden="true"></i>&nbsp; {{total_files}}&nbsp;Folder{{total_files|pluralize}}&nbsp;<i class="fa fa-arrows-h" aria-hidden="true"></i>&nbsp;<i class="fa fa-file" aria-hidden="true"></i>&nbsp;{{total_total}}&nbsp;File{{total_total|pluralize}}
				</td> 
			</tr>  
		</table>
	
	<p>
	<span class="pull-left">
			<a href="javascript:history.go(-1)" onMouseOver="self.status.referrer;return true"><button type="button" class="btn btn-primary btn-xs"><i class="fa fa-angle-double-left" aria-hidden="true"></i>&nbsp;Go Back</button></a> </span>
		<span class="pull-right">
		<a href="{% url 'BeginningDash:pdf' %}"><button type="button" class="btn btn-primary btn-xs"><i class="fa fa-file-pdf-o" aria-hidden="true" title="DOWNLOAD SUMMARY PDF NOW"></i>&nbsp;Download Sum. PDF</button></a>
	</span>
	</p>  
	<br>
</div>
<div class="col-md-12">
	<hr>
  <div align="middle" style="background-color: #0081b5; padding: 12px;border-radius: 10px;">
	<div align="middle" style="color: whitesmoke; font-size:20px; font-weight: bold; font-family: 'satisfyregular'"><i class="fa fa-spinner fa-pulse fa-3x fa-fw" style="font-size: 19px;"></i>
	<span class="sr-only">Loading...</span>Count Down To Main Event XD
	</div>
	 <div style="text-shadow: 1px 15px 7px rgba(0,0,0,0.5); font-size:23px; color: gold;" id="countdown" >
	   <i class="fa fa-calendar-check-o" aria-hidden="true"></i><span id="days"></span> Days 
	   <i class="fa fa-arrow-circle-right" aria-hidden="true"></i><span id="hours"> </span> Hours
	   <i class="fa fa-arrow-circle-right" aria-hidden="true"></i><span id="minutes"> </span>  Minutes
	   <i class="fa fa-arrow-circle-right" aria-hidden="true"></i><span id="seconds"> </span> Seconds 



	 </div>
	 </div>
	 <br>
	 <hr>
	 <script type="text/javascript">

      function countdown(){
        var now = new Date();
        var eventDate = new Date(2019,  00,  01, 16, 00,  00, 00)

        var currentTime = now.getTime();
        var eventTime = eventDate.getTime();
        

        var remTime = eventTime - currentTime;
        if (remTime  <= 0  )(
              $('#countdown').text('HAPPY NEW YEAR LUCKY PIUS!!!! ')
          )
        

        var s = Math.floor(remTime / 1000);
        var m = Math.floor(s / 60);
        var h = Math.floor(m / 60);
        var d = Math.floor(h / 24);

        h %= 24;
        m %= 60;
        s %= 60;

        h = (h < 10) ? "0" + h : h;
        m = (m < 10) ? "0" + m : m;
        s = (s < 10) ? "0" + s : s;

        document.getElementById("days").textContent = d;
        document.getElementById("days").innerText = d;

        document.getElementById("hours").textContent = h;
        document.getElementById("minutes").textContent = m;
        document.getElementById("seconds").textContent = s;

        setTimeout(countdown, 1000);

        
      }

      countdown();
    </script>


	
</div>


	{% endblock content %}

templates/Additions/GalleryUpload.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="col-md-12">
<style type="text/css">
	div#scarf{
			margin-left: -26px;
			padding-right:-30px;
			margin-right:30px;
		}
	div#scarf2{
		margin-left: -26px;
		margin-right:-25px;
		
}
</style>
<div class="container">{% include 'partials/marquee4gallery.html' %}</div>
	

</div>
<div class="container">
<div class="row">
<div class="col-md-6">
    <div align="middle">
    <div style="background-color: black; color: whitesmoke;border-radius: 5px;y">You Have {{total_vids}} Video{{total_vids|pluralize}} </div>
	<h3 style="background-color: black; color: whitesmoke; border-width: 5px; border-style: groove; font-family: 'black_ops_oneregular'; "><span class="glyphicon glyphicon-star" aria-hidden="true"></span>&nbsp;VIDEOS</h3>
	<p> 
	{% for item in item %}
	  {% if item.vids %}
	  <b>{{item.vids|linebreaks|slice:"11:"}}</b>
        <div class="embed-responsive embed-responsive-16by9">
                <video controls class="embed-responsive-item" preload="metadata" src='{{ item.vids.url }}' style="border-radius: 10px; border-style: groove;border-width: 3px;"></video>
        </div><br>
         <hr>
        <hr>
        {% endif %}
        {% empty %}
        <div class="well well-sm"><p align="middle">Your Video Gallery Is Empty, <a href="{% url 'BeginningDash:home' %}"> Upload Videos</a> To See Them Here!</p></div>
        
       {% endfor %}

	</p>
	</div> <!-- for align middle -->
</div>
<div class="col-md-3">
<div align="middle">
	<h3 style="background-color: black; color: whitesmoke; border-width: 5px; border-style: groove; font-family: 'black_ops_oneregular'; "><i class="fa fa-picture-o" aria-hidden="true"></i>&nbsp;IMAGES&nbsp;<span class="badge" style="color: gold; background-color: black;">NEW</span></h3>
	<p>
		{% for item in item|slice:":2" %}
	     {% if item.imgs %}
	  
	    <div class="row">
		  <div class="col-sm-6 col-md-12">
		    <div class="thumbnail">
		              <img src="{{item.imgs.url}}"><br>
		      <div class="caption">
		       {{item.imgs|linebreaks|slice:"11:"}}
		      </div>
		    </div>
		  </div>
		</div>
        <hr>
        <hr>
        {% endif %}
         {% empty %}
        <div class="well well-sm"><p align="middle">No New Images, <a href="{% url 'BeginningDash:home' %}"> Upload Images</a> To See Them Here!</p></div>
        
       {% endfor %}
	</p>
</div> <!-- for align middle -->
</div>


<div class="col-md-3">
<div align="middle">
	<h3 style="background-color: black; color: whitesmoke; border-width: 5px; border-style: groove; font-family: 'black_ops_oneregular'; "><i class="fa fa-picture-o" aria-hidden="true"></i>&nbsp;IMAGES&nbsp;<span class="badge" style="color: red; background-color: black;">OLD</span></h3>
	<p>
		{% for item in item|slice:"5:" %}
	     {% if item.imgs %}
	  
	    <div class="row">
		  <div class="col-sm-6 col-md-12">
		    <div class="thumbnail">
		              <img src="{{item.imgs.url}}"><br>
		      <div class="caption">
		       {{item.imgs|linebreaks|slice:"11:"}}
		      </div>
		    </div>
		  </div>
		</div>
        <hr>
        <hr>
        {% endif %}
         {% empty %}
        <div class="well well-sm"><p align="middle">No old Images, <a href="{% url 'BeginningDash:home' %}"> Upload Images</a> To See Them Here!</p></div>
        
       {% endfor %}
	</p>

</div> <!-- for align middle -->

</div>
</div> <!-- for row -->
</div>
<hr>
<hr>
{% endblock content %}

templates/Additions/sumPDFtemp.html
{% load static %}
<!-- # context processors doesnt power a pdf -->
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
 <html>
     <head>



  
         <title>Title</title>
         <style type="text/css">
             body {
                 font-weight: 200;
                 font-size: 14px;
                 background-color:blue;
                 color: whitesmoke;
             }
             .header {
                 font-size: 20px;
                 font-weight: 100;
                 text-align: center;
                 color: #007cae;
             }
             .title {
                 font-size: 10px;
                 font-weight: bold;
                /* text-align: right;*/
                padding: 10px 20px 0px 20px; 
                background-color: #708090;
                color: whitesmoke;
               
             }
             .title span {
                 color: #007cae;
             }
             .details {
                 padding: 10px 20px 0px 20px;
                 text-align: left !important;
                 font-size: 13px;
                 background-color:#7A8B8B;
                 color: whitesmoke;
                 /*margin-left: 40%;*/
             }
             .hrItem {
                 border: none;
                 height: 1px;
                 /* Set the hr color */
                 color: #333; /* old IE */
                 background-color: #fff; /* Modern Browsers */
             }
         </style>
     </head>
     <body>
         <div class='wrapper'>
         
             <div class='header'>
                 
                 <p class='title' >*** SUMMARY PDF FOR ALL UPLOADED CONTENTS ***</p>
                 <hr>
             </div>
         <div>
         <div class='details'>
             ** Dear Esteemed <b style="text-decoration: underline; text-transform: lowercase;"><a href="http://localhost:3333/profile/" style="color: gold;text-decoration: none;">{{member_name}}</a></b>,&nbsp;thank you for patronizing <a href="http://localhost:3333/home/dashboard/" style="color: gold;text-decoration: none;"> DashNG's</a> services, we appreciate your time.<br>
             ** Below is the data summary statistics for {{today}}.<br>
             ** You have uploaded {{total_files}} folder{{ total_files|pluralize }} so far.
            <!--  ____________________________________________ -->
            <table  class="table table-condensed" border='1' cellpadding='10' cellspacing='10' style="color: whitesmoke;background-color: #708090;"> 
        <tr>
            <th colspan='3'><p align="middle"><b  class="warning"><button class="btn btn-info disabled" type="button">
            <b>FILE SUMMARY</b> <span class="badge">{{total_files}}</span>
            </button></b></p></th>
        </tr>
        <tr class="warning">
            <th> DATA TYPE </th>
            <th>DATE-TIME CREATED</th>
            <th>FILES</th>
        </tr>
        <tr class="info">
            <td>File Group(ID)</td>
            <td>{% for item in item %}
                {% if item.creates %}
                {{item.creates}}<br>
                {% endif %}
                {% endfor %}
            </td>
            <td>{% for item in item %}
                {% if item.file_g %}
                {{item.file_g}}<br>
                {% endif %}
                {% endfor %}
            </td> 
        </tr>

        <tr class="warning">
            <td>VIDEOS</td>
            <td><i class="fa fa-lightbulb-o" aria-hidden="true"></i>&nbsp;{{total_vids}}&nbsp;Video{{total_vids|pluralize}}</td>
            <td>

                {% for item in item %}
                {% if item.vids %}
                {{item.vids|truncatechars_html:42|slice:"8:"|cut:"-"|cut:"_"}}
                {% endif %}
                {% endfor %}

            </td>
            <tr class="info">
                <td>AUDIOS</td>
                <td><i class="fa fa-lightbulb-o" aria-hidden="true"></i>&nbsp;{{total_auds}}&nbsp;Audio{{total_auds|pluralize}}</td>
                <td>{% for item in item %}
                    {% if item.auds %}
                    <span class="glyphicon glyphicon-headphones"></span>&nbsp;{{item.auds|truncatechars_html:42|slice:"11:"|cut:"-"|cut:"_"}}
                    {% endif %}
                    {% endfor %}
                </td>
            </tr> 
            <tr class="warning">     
                <td>IMAGES</td>   
                <td><i class="fa fa-lightbulb-o" aria-hidden="true"></i>&nbsp;{{total_imgs}}&nbsp;Image{{total_imgs|pluralize}}</td>  
                <td>{% for item in item %}
                    {% if item.imgs %}
                    <span class="glyphicon glyphicon-picture"></span>&nbsp;{{item.imgs|truncatechars_html:42|slice:"8:"|cut:"-"|cut:"_"}}
                    {% endif %}
                    {% endfor %}
                </td> 
            </tr> 
            <tr class="warning">     
                <td>PDFS</td>   
                <td><i class="fa fa-lightbulb-o" aria-hidden="true"></i>&nbsp;{{total_pdfs}}&nbsp;Pdf{{total_pdfs|pluralize}}</td>  
                <td>{% for item in item %}
                    {% if item.pdfs %}
                    <i class="fa fa-file-pdf-o" aria-hidden="true"></i>&nbsp;{{item.pdfs|truncatechars_html:42|slice:"8:"|cut:"-"|cut:"_"}}
                    {% endif %}
                    {% endfor %}
                </td> 
            </tr> 
            <tr class="warning">     
                <td>TOTAL</td>   
                <td><i class="fa fa-file" aria-hidden="true"></i>&nbsp;{{total_total}}&nbsp;File{{total_total|pluralize}}</td>  
                <td>
                 <i class="fa fa-folder-open" aria-hidden="true"></i>&nbsp; {{total_files}}&nbsp;Folder{{total_files|pluralize}}&nbsp;<i class="fa fa-arrows-h" aria-hidden="true"></i>&nbsp;<i class="fa fa-file" aria-hidden="true"></i>&nbsp;{{total_total}}&nbsp;File{{total_total|pluralize}}
                </td> 
            </tr>  
        </table>
            <!--  ____________________________________________ -->

             <hr class='hrItem' />
         </div>
     </div>
     </body>
 </html>