BeginningDash/urls.py
from django.conf.urls import url
from BeginningDash import views
from django.contrib.auth import views as myviews
from BeginningDash.views import GeneratePDF
from BeginningDash.views import GeneratePDF_4_code
from django.contrib.auth.models import User
from django.contrib.auth.views import (
	password_reset,
	password_reset_done, 
	password_reset_confirm,
	password_reset_complete
 )

app_name = 'BeginningDash'
urlpatterns = [
	url(r'^contact-us/', views.mycontact, name="contact"),
	url(r'^aboutus/', views.aboutus, name="aboutus"),
	url(r'^aboutfornonuser/', views.aboutfornonuser, name="aboutfornonuser"),
	url(r'^mycontact4offlineuser/', views.mycontact4offlineuser, name="mycontact4offlineuser"),
	url(r'^home/dashboard/$', views.homepage, name="home"),
	url(r'^coding/now/$', views.UCU, name="code"),
	url(r'^all/files/upload/$', views.AllFilesUploaded, name="allfiles"),
	url(r'^all/codes/upload/$', views.AllCodesUploaded, name="allcodes"),
	url(r'^media/upload/$', views.MediaUploaded, name="gallery"),
	url(r'^uploadpdf/$', GeneratePDF.as_view(),name="pdf"),
	url(r'^uploadpdf/code/$', GeneratePDF_4_code.as_view(),name="pdf_code"),
	url(r'^created_document/$', views.created_document, name='created_document'),
	url(r'^profile/$', views.view_profile, name="view_profile"),
	url(r'^user/profile/edit/$', views.edit_profile, name='edit_profile'),
	url(r'^account/logout/$', views.logout,name="logout"),
	url(r'^(?P<upload_id>[0-9]+)/delete/files$', views.upload_delete, name="delete_upload"),
	url(r'^(?P<code_id>[0-9]+)/delete/codes$', views.code_delete, name="delete_code"),
	url(r'^login-reg/', views.loginX_regX, name='loginX_regX'),	
	url(r'^register/response/', views.register_response, name='reg_response'),
	url(r'^change-password/$', views.change_password, name='change_password'),
	url(r'^reset-password/$', password_reset,
		{ "template_name":"Beginning/reset_password.html","post_reset_redirect":"BeginningDash:password_reset_done",
		"email_template_name":"Beginning/reset_password_email.html"},
		name='reset_password'),
	url(r'^reset-password/done/$', password_reset_done,{"template_name":"Beginning/reset_password_done.html"},name='password_reset_done'),
	url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', password_reset_confirm,{"post_reset_redirect":"BeginningDash:password_reset_complete","template_name":"Beginning/reset_password_confirm.html"}, name='password_reset_confirm' ),
	url(r'^reset-password/complete/$', password_reset_complete,{"template_name":"Beginning/reset_password_complete.html"},name="password_reset_complete")
]

DashNig/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from BeginningDash import urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('BeginningDash.urls', namespace="BeginningDash")),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/partials/codemarquee.html
<div id="scarf" class="alert alert-info hidden-xs hidden-sm" role="alert"><marquee scrollamount="3"><b>Hey Programmer, You Have The Priviledge To Upload Two(2) Document(Doc.) Type in every session And Space-Limit-Size Of 500 Megabytes(MB). Upgrade To Premuim To Get Unlimited Space Access And Inclusion Of Several Programming Files Like Python(.py) etc. </b></marquee></div>
<div id="scarf2" class="alert alert-info hidden-lg hidden-md" role="alert"><marquee scrollamount="3" ><b>As A Free User, You Have The Priviledge To Upload Four(4) Document(Doc.) Type in every session And Space-Limit-Size Of 500 Megabytes(MB). Upgrade To Premuim To Get Unlimited Space Access  And Inclusion Of Several Programming Files Like Python(.py) etc.</b></marquee></div>

templates/partials/custommessage.html
			
{% if file_error_message %}
<div class="alert alert-danger alert-dismissible" role="alert">
	<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true"><i class="fa fa-times-circle" aria-hidden="true" style="color: black;"></i></span></button>
	<strong><i class="fa fa-warning" aria-hidden="true" ></i>&nbsp;{{ file_error_message  }}</strong>
</div>
{% endif %}

{% if file_success_message %}
<div class="alert alert-success alert-dismissible" role="alert">
	<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true"><i class="fa fa-times-circle" aria-hidden="true" style="color: black;"></i></span></button>
	<strong><i class="fa fa-cloud-upload" aria-hidden="true"></i>&nbsp;{{ file_success_message }}</strong>
</div>
{% endif %}
{% if myerrormessage %}
<div class="alert alert-danger alert-dismissible" role="alert">
	<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true"><i class="fa fa-times-circle" aria-hidden="true" style="color: black;"></i></span></button>
	<strong><i class="fa fa-warning" aria-hidden="true" ></i>&nbsp;{{ myerrormessage  }}</strong>
</div>
{% endif %}

{% if mysuccessmessage %}
<div class="alert alert-success alert-dismissible" role="alert">
	<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true"><i class="fa fa-times-circle" aria-hidden="true" style="color: black;"></i></span></button>
	<strong><i class="fa fa-cloud-upload" aria-hidden="true"></i>&nbsp;{{ mysuccessmessage }}</strong>
</div>
{% endif %}
{% if error_msg %}
<div class="alert alert-danger alert-dismissible" role="alert" align="middle">
	<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true"><i class="fa fa-times-circle" aria-hidden="true" style="color: black;"></i></span></button>
	<strong><i class="fa fa-warning" aria-hidden="true" ></i>&nbsp;{{ error_msg }}</strong>
</div>
{% endif %}



{% if success_msg %}
<div class="alert alert-success alert-dismissible" role="alert" align="middle">
	<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true"><i class="fa fa-times-circle" aria-hidden="true" style="color: black;"></i></span></button>
	<strong><i class="fa fa-cloud-upload" aria-hidden="true"></i>&nbsp;{{ success_msg }}</strong>
</div>
{% endif %}




 <script>
 $(document).ready(function() {
 	$(window).load(function(){
 		$("#mywork").hide()
 	})
 	});
 </script>

templates/partials/marquee4gallery.html
<div id="scarf" class="alert alert-warning hidden-xs hidden-sm" role="alert"><marquee scrollamount="3"><b><i class="fa fa-television" aria-hidden="true"></i>&nbsp;Gallery Section Renders Your Media Files Only, DashNG Provides Access To VIDEO And IMAGE FILES, Five Files Based On Recency And  Anciency Are Displayed  Here In Your Gallery. </b></marquee></div>
<div id="scarf2" class="alert alert-warning hidden-lg hidden-md" role="alert"><marquee scrollamount="3" ><b><i class="fa fa-television" aria-hidden="true"></i>&nbsp;Gallery Section Renders Your Media Files Only, DashNG Provides Access To VIDEO And IMAGE FILES, Five Files Based On Recency And  Anciency Are Displayed Here In Your Gallery. </b></marquee></div>

templates/partials/modal4codes.html
{% load crispy_forms_tags %}
<div class="modal fade" id="codes" tabindex="-1" role="dialog" aria-labelledby="gridSystemModalLabel" style="padding-right: 17px;">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        
        <h4 class="modal-title" id="gridSystemModalLabel"> Ready to Have A Little Taste Of Premium?</h4>
      </div>
      <div class="modal-body">
   
          <form action="." method="post" enctype="multipart/form-data" id="uploadform">    {{code_form|crispy}}  {% csrf_token %}
          <br>
            <div class="modal-footer">
             <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
            <button type="submit" class="btn btn-primary">Upload Codes</button>
           </div>
          </form>

      </div>
      
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

templates/partials/modal4delete.html
<div class="modal fade" id="delete" tabindex="-1" role="dialog" aria-labelledby="gridSystemModalLabel" style="padding-right: 17px;">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
      <div class="hidden-xs hidden-sm hidden-md">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h5 class="modal-title" id="gridSystemModalLabel" style="color: red;"> &nbsp;&nbsp;<i class="fa fa-recycle" aria-hidden="true"></i>&nbsp;Ready to Delete Video(s)?</h5>
      </div>
      <div class="modal-body hidden-xs hidden-sm hidden-md">
          <p>Select "Delete Folder" below if you are ready to delete the entire item(s) in the folder.</p>

      </div>
      <div class="modal-footer hidden-xs hidden-sm hidden-md" >
        <button type="button" class="btn btn-secondary btn-xs" data-dismiss="modal">Cancel</button>
         <button type="submit" class="btn btn-danger btn-xs">
          <span class="glyphicon glyphicon-trash"></span>&nbsp; Delete Folder
          </button>
      </div> <!-- for hidden -->
      </div>
      <div class="modal-header">
       <div class="hidden-lg">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h6 class="modal-title pull-left" id="gridSystemModalLabel" style="color: red;"> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<i class="fa fa-recycle" aria-hidden="true"></i>&nbsp;Ready to Delete Video(s)?</h6>
      </div><br>
      <div class="modal-body hidden-lg " >
          <h6 class="small pull-left">Select "Delete Folder" below<br> if you are ready to delete<br> the entire item(s) in the folder.</h6>
          <br><br>
      </div>
      <div class="modal-footer pull-left hidden-lg">
      <hr>
        <button type="button" class="btn btn-secondary btn-xs" data-dismiss="modal">Cancel</button>
         <button type="submit" class="btn btn-danger btn-xs">
          <span class="glyphicon glyphicon-trash"></span>&nbsp; Delete Folder
          </button>
      <hr>
      </div>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

templates/partials/modal4logout.html
<div class="modal fade" id="logout" tabindex="-1" role="dialog" aria-labelledby="gridSystemModalLabel" style="padding-right: 17px;">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="gridSystemModalLabel"> Ready to Leave?</h4>
      </div>
      <div class="modal-body">
          <p>Select "Logout" below if you are ready to end your current session.</p>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
         <a href="{% url 'BeginningDash:logout' %}"><button type="button" class="btn btn-primary"><span class="glyphicon glyphicon-log-out"></span> Logout</button></a>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

templates/partials/nav.html
 <!--  ___________________________________________________________________________________________________________________  STARTNAV-->
 {% load static %}
  {% url "BeginningDash:begin" as begin %} 
  {% url "BeginningDash:home" as home %} 
  {% url "BeginningDash:view_profile" as viewprofile %} 
  {% url "BeginningDash:logout" as logout %} 
  {% url "BeginningDash:signup" as signup %} 
  {% url "BeginningDash:code" as code %} 
  {% url "BeginningDash:code_files" as code_files %} 
  {% url "BeginningDash:allfiles" as file_files %} 
  {% url "BeginningDash:gallery" as gallery %} 
  {% url "BeginningDash:contact" as contact %} 
  {% url "BeginningDash:created_document" as created_document %}

 {% if not user.is_authenticated %}       
 <div class="h-top" id="home">
   <div class="top-header">
    <ul class="cl-effect-16 top-nag">
      <li><a {% if request.path == signup %}  class="active" {% endif %} href="" data-hover="REGISTRATION">REGISTRATION</a>
      </li> 
      <li><a href="" data-hover="ABOUT">ABOUT</a></li>
      <li><a href="" data-hover="SERVICES">SERVICES</a></li>
      <li><a href="" data-hover="CONTACT">CONTACT</a></li>
      <li><a href="{% url 'BeginningDash:begin' %}" data-hover="LOGIN">LOGIN</a></li> 
    </ul>
   

    <div class="clearfix"></div>
  </div>
</div>
<div class="full">
  <div class="col-md-3 top-nav register" style="position: fixed;" >
   <div class="logo">
    <a {% if request.path == home %} style="background-color: black;" {% endif %} href="{% url 'BeginningDash:home' %}" ><h1 style="color: whitesmoke;">DashNG</h1></a>
     <a class="btn btn-info  hidden-lg hidden-md" role="button" data-toggle="collapse" href="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
        MENU
    </a>
    <div class="collapse hidden-lg hidden-md hidden-sm " id="collapseExample">
      <div class="well">
        <ul class="cl-effect-16 ">
        <li   {% if request.path == home %} class="active" {% endif %} ><a href="{% url 'BeginningDash:home' %}" data-hover="HOME" >HOME</a></li> 
        <li><a href="" data-hover="ABOUT">ABOUT</a></li> 
        <li><a href="" data-hover="GALLERY">GALLERY</a></li>
        <li><a href="" data-hover="CONTACT">CONTACT</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="top-menu">
   <ul class="cl-effect-16  hidden-xs">
    <li><a  {% if request.path == home %} class="active" {% endif %} href="{% url 'BeginningDash:home' %}" data-hover="HOME">HOME</a></li> 
    <li><a href="" data-hover="ABOUT">ABOUT</a></li>
    <li  ><a {% if request.path == code %} class="active" {% endif %}  href="{% url 'BeginningDash:code' %}" data-hover="CODES">CODES</a></li>
    <li><a href="" data-hover="SERVICES">SERVICES</a></li>
    <li><a href="" data-hover="GALLERY">GALLERY</a></li>
    <li><a href="" data-hover="CONTACT">CONTACT</a></li>
  </ul>
 
  <ul class="side-icons">
    <li><a class="fb" href="#"></a></li>
    <li><a class="twitt" href="#"></a></li>
    <li><a class="goog" href="#"></a></li>
    <li><a class="drib" href="#"></a></li>
  </ul>
</div>
</div>
</div>

{% else %}

  <div class="h-top" id="home">
   <div class="top-header">
    <ul class="cl-effect-16 top-nag navbar-left">
      <li><a  {% if request.path == home %} class="active" {% endif %} href="{% url 'BeginningDash:home' %}" data-hover="HOME">HOME</a></li> 
      <li><a href="l" data-hover="ABOUT">ABOUT</a></li>
      <li><a href="" data-hover="CONTACT">CONTACT</a></li>
       <li><a href="" data-hover="UPGRADE">UPGRADE<sup style="font-size: 10px;" class="hidden-xs">TM</sup></a></li>
    </ul>
    <ul class="cl-effect-16 top-nag navbar-right" >
    <style type="text/css">
      a#hover:hover{
        color: red;
        background-color: white;
        cursor: pointer;
      }
      a#drop{
        color: whitesmoke;
        background-color: black;
      }
      a#drop:hover{
        color: black;
        background-color: whitesmoke;
      }

    </style>
      <li class="dropdown">
        <a  {% if request.path == viewprofile %} class="active" {% endif %} class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">CORE<span class="caret"></span></a>
        <ul class="dropdown-menu" style="background-color:#4a245e;">
          
          <li><a id="drop" href="{% url 'BeginningDash:view_profile' %}"><i class="fa fa-inbox" aria-hidden="true"></i>&nbsp;CORE&nbsp;DASHBOARD&nbsp;<span class="badge">{{news_count}}</span></a></li>
          <li><a id="drop" class="reloadpage" href="#"><i class="fa fa-refresh" aria-hidden="true"></i>&nbsp;REFRESH PAGE&nbsp;&nbsp;<span class="badge" style="color: red;">Hot</span></a></li>
          
        </ul>
      </li>
      <li><a href="" data-hover="DONATE">DONATE</a></li>
     <li><a  cl {% if request.path == code %} class="active" {% endif %} ass= "nav-link" href="{% url 'BeginningDash:code' %}" id="hover"><i class="fa fa-code" aria-hidden="true"></i>&nbsp;CODES</a></li>
      <li class="pull-right"><a class= "nav-link" data-toggle="modal" data-target="#logout" id="hover"><i class="fa fa-sign-out" aria-hidden="true"></i>&nbsp;SIGNOUT</a></li>
      
    </ul>
     {% include 'partials/modal4logout.html' %}
     {% include 'partials/modal4codes.html' %}
    <div class="clearfix"></div>
  </div>
</div>
<div class="full">


 

  <div class="col-md-3 top-nav register" style="height: 100%">
   <div class="logo">
   <div align="middle"><span><b><i class="fa fa-user-circle-o" aria-hidden="true"></i>&nbsp;<span >USER STATUS</span></b></div><button type="button" class="btn btn-success btn-lg btn-block" disabled="disabled"><i class="fa fa-question-circle-o" aria-hidden="true"></i>&nbsp; {{user_status}}</button></span><br>
    <div align="middle"><a href="{% url 'BeginningDash:home' %}" class="logo"><img id="logo" src="{% static 'logo/dash.jpg' %}"  alt=""></a></div>
        <a class="btn btn-info  hidden-lg hidden-md hidden-sm" role="button" data-toggle="collapse" href="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
        MENU
    </a>

    <div class="collapse hidden-lg hidden-md hidden-sm " id="collapseExample">
      <div class="well">
        <ul class="cl-effect-16 ">
        <li   {% if request.path == home %} class="active" {% endif %} ><a href="{% url 'BeginningDash:home' %}" class="active" data-hover="HOME" >HOME</a></li> 
        <li><a href="" data-hover="ABOUT">ABOUT</a></li>
        <li ><a {% if request.path == code %} class="active" {% endif %}  href="{% url 'BeginningDash:code' %}" data-hover="CODES">CODES</a></li>
         <li><a href="" data-hover="CUBU"><span title="Codes Uploaded By {{user}} ">CUBU</span></a></li>
        <li  ><a href="{% url 'BeginningDash:allfiles' %}" data-hover="FUBU"><span title="Files Uploaded By  {{user}}">FUBU</span></a></li>
        <li><a href="" data-hover="GALLERY">GALLERY</a></li>
        <li><a href="" data-hover="CONTACT">CONTACT</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="top-menu">

   <ul class="cl-effect-16">
    <li><a  {% if request.path == home %} class="active" {% endif %} href="{% url 'BeginningDash:home' %}" data-hover="HOME"><span title="GoTo Files Upload page.">HOME</span></a></li> 
    <li><a href="about.html" data-hover="ABOUT"><span title="Check out About DashNG.">ABOUT</span></a></li>
    <li  ><a {% if request.path == code %} class="active" {% endif %}  href="{% url 'BeginningDash:code' %}" data-hover="CODES"><span title="GoTo the Codes' page.">CODES</span></a></li>
     <li><a href="" data-hover="[ CUBU ]"><span title="Codes Uploaded By {{user}} ">[ CUBU ]</span></a></li>
      <li ><a href="{% url 'BeginningDash:allfiles' %}" data-hover="[ FUBU ]" {% if request.path == file_files %} class="active" {% endif %} ><span title="Files Uploaded By  {{user}}">[ FUBU ]</span></a></li>
    <li><a href="{% url 'BeginningDash:gallery' %}"  data-hover="GALLERY"  {% if request.path == gallery %} class="active" {% endif %}><span title="{{user}}'s Gallery">GALLERY</span></a></li>
    <li><a href="{% url 'BeginningDash:contact' %}" data-hover="CONTACT"><span title="Contact DashNG anytime.">CONTACT</span></a></li>
  </ul>

   
  <ul class="side-icons">
    <li><a class="fb" href="#"></a></li>
    <li><a class="twitt" href="#"></a></li>
    <li><a class="goog" href="#"></a></li>
    <li><a class="drib" href="#"></a></li>
  </ul>
</div>
</div>
</div>

{% endif %}
<!--  ___________________________________________________________________________________________________________________  ENDNAV-->

templates/partials/well_4_css.html
<div class="collapse" id="forcss">
  <div class=" well">
  <!--   <h3>{{ files }}</h3> -->
	{% for file in code_files %} 
	{% if file %}
    {% if file.CSS %}
	<b><i class="fa fa-css3" aria-hidden="true"></i>&nbsp;Upload {{file.id}}</b><br>
	<b><i class="fa fa-folder-o" aria-hidden="true"></i>&nbsp;Directory :: </b>&nbsp; {{file.folder}} <br>
	
	 <b><i class="fa fa-code" aria-hidden="true"></i>&nbsp;CSS Title :: </b>&nbsp;<span id="vidname" data-toggle="modal" data-target="#{{file.CSS.size}}" title="Click For More Details "> {{file.CSS.name|safe|truncatechars_html:25|slice:"8:"}}&nbsp;<i class="fa fa-eercast" aria-hidden="true"></i></span> <br>   
	   {% include 'partials/modal4css.html' %}
	<b><i class="fa fa-file-o" aria-hidden="true"></i>&nbsp;CSS Size :: </b>&nbsp; {{file.CSS.size|filesizeformat}}
	<br> 
	<div class="pull-left" >  
	<form action="{% url 'BeginningDash:delete_code' file.id %}" method="post" style="display: inline;">
	{% csrf_token %}
	<input type="hidden" name="code_id" value="{{ file.id }}" />
	<button type="button" class="btn btn-danger btn-xs" data-toggle="modal" data-target="#delete"><span class="glyphicon glyphicon-remove"></span>&nbsp; Delete Folder</button>
	{% include 'partials/modal4delete.html' %}
	</form>
	
	</div><br>
    <hr id="hori">
	{% endif %}
	{% endif %}
	{% empty %}
        <i class="fa fa-question-circle-o" aria-hidden="true"></i>&nbsp;{{Empty_File}}
	{% endfor %}
  </div>
</div>

templates/partials/well_4_imgs.html
<div class="collapse" id="forimgs">
  <div class=" well">
  <!--   <h3>{{ files }}</h3> -->
	{% for file in files %} 
	{% if file %}
    {% if file.IMAGE %}
	<b><i class="fa fa-picture-o" aria-hidden="true"></i>&nbsp;Upload {{file.id}}</b><br>
	<b><i class="fa fa-folder-o" aria-hidden="true"></i>&nbsp;Directory :: </b>&nbsp; {{file.file_group}} <br>
	
	 <b><i class="fa fa-file-image-o" aria-hidden="true"></i>&nbsp;Image Title :: </b>&nbsp;<span id="vidname" data-toggle="modal" data-target="#{{file.IMAGE.size}}" title="Click For More Details "> {{file.IMAGE.name|safe|truncatechars_html:25|slice:"8:"}}&nbsp;<i class="fa fa-eercast" aria-hidden="true"></i></span> <br>   
	   {% include 'partials/modal4imgs.html' %}
	<b><i class="fa fa-file-o" aria-hidden="true"></i>&nbsp;Image Size :: </b>&nbsp; {{file.IMAGE.size|filesizeformat}}
	<br> 
	<div class="pull-left" >  
	<form action="{% url 'BeginningDash:delete_upload' file.id %}" method="post" style="display: inline;">
	{% csrf_token %}
	<input type="hidden" name="upload_id" value="{{ file.id }}" />
	<button type="button" class="btn btn-danger btn-xs" data-toggle="modal" data-target="#delete4img"><span class="glyphicon glyphicon-remove"></span>&nbsp; Delete Folder</button>
	{% include 'partials/modal4delete4.html' %}
	</form>
	
	</div><br>
    <hr id="hori">
	{% endif %}
	{% endif %}
	{% empty %}
        <i class="fa fa-question-circle-o" aria-hidden="true"></i>&nbsp;{{Empty_File}}
	{% endfor %}
  </div>
</div>

templates/partials/well_4_videos.html
<div class="collapse" id="forvids">
  <div class=" well">
  <!--   <h3>{{ files }}</h3> -->
	{% for file in files %} 
	{% if file %}
    {% if file.VIDEO %}
	<b><i class="fa fa-film" aria-hidden="true"></i>&nbsp;Upload {{file.id}}</b><br>
	<b><i class="fa fa-folder-o" aria-hidden="true"></i>&nbsp;Directory :: </b>&nbsp; {{file.file_group}} <br>
	
	 <b><i class="fa fa-file-video-o" aria-hidden="true"></i>&nbsp;Image Title :: </b>&nbsp;<span id="vidname" data-toggle="modal" data-target="#{{file.VIDEO.size}}" title="Click For More Details "> {{file.VIDEO.name|safe|truncatechars_html:25|slice:"8:"}}&nbsp;<i class="fa fa-eercast" aria-hidden="true"></i></span> <br>   
	   {% include 'partials/modal4vids.html' %}
	<b><i class="fa fa-file-o" aria-hidden="true"></i>&nbsp;Image Size :: </b>&nbsp; {{file.VIDEO.size|filesizeformat}}
	<br> 
	<div class="pull-left" >  
	<form action="{% url 'BeginningDash:delete_upload' file.id %}" method="post" style="display: inline;">
	{% csrf_token %}
	<input type="hidden" name="upload_id" value="{{ file.id }}" />
	<button type="button" class="btn btn-danger btn-xs" data-toggle="modal" data-target="#delete"><span class="glyphicon glyphicon-remove"></span>&nbsp; Delete Folder</button>
	{% include 'partials/modal4delete.html' %}
	</form>
	
	</div><br>
    <hr id="hori">
	{% endif %}
	{% endif %}
	{% empty %}
        <i class="fa fa-question-circle-o" aria-hidden="true"></i>&nbsp;{{Empty_File}}
	{% endfor %}
  </div>
</div>