BeginningDash/urls.py
from django.conf.urls import url
from BeginningDash import views
from django.contrib.auth import views as myviews
from BeginningDash.views import GeneratePDF
from BeginningDash.views import GeneratePDF_4_code
from django.contrib.auth.models import User
from django.contrib.auth.views import (
	password_reset,
	password_reset_done, 
	password_reset_confirm,
	password_reset_complete
 )

app_name = 'BeginningDash'
urlpatterns = [
	url(r'^contact-us/', views.mycontact, name="contact"),
	url(r'^aboutus/', views.aboutus, name="aboutus"),
	url(r'^aboutfornonuser/', views.aboutfornonuser, name="aboutfornonuser"),
	url(r'^mycontact4offlineuser/', views.mycontact4offlineuser, name="mycontact4offlineuser"),
	url(r'^home/dashboard/$', views.homepage, name="home"),
	url(r'^coding/now/$', views.UCU, name="code"),
	url(r'^all/files/upload/$', views.AllFilesUploaded, name="allfiles"),
	url(r'^all/codes/upload/$', views.AllCodesUploaded, name="allcodes"),
	url(r'^media/upload/$', views.MediaUploaded, name="gallery"),
	url(r'^uploadpdf/$', GeneratePDF.as_view(),name="pdf"),
	url(r'^uploadpdf/code/$', GeneratePDF_4_code.as_view(),name="pdf_code"),
	url(r'^created_document/$', views.created_document, name='created_document'),
	url(r'^profile/$', views.view_profile, name="view_profile"),
	url(r'^user/profile/edit/$', views.edit_profile, name='edit_profile'),
	url(r'^account/logout/$', views.logout,name="logout"),
	url(r'^(?P<upload_id>[0-9]+)/delete/files$', views.upload_delete, name="delete_upload"),
	url(r'^(?P<code_id>[0-9]+)/delete/codes$', views.code_delete, name="delete_code"),
	url(r'^login-reg/', views.loginX_regX, name='loginX_regX'),	
	url(r'^register/response/', views.register_response, name='reg_response'),
	url(r'^change-password/$', views.change_password, name='change_password'),
	url(r'^reset-password/$', password_reset,
		{ "template_name":"Beginning/reset_password.html","post_reset_redirect":"BeginningDash:password_reset_done",
		"email_template_name":"Beginning/reset_password_email.html"},
		name='reset_password'),
	url(r'^reset-password/done/$', password_reset_done,{"template_name":"Beginning/reset_password_done.html"},name='password_reset_done'),
	url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', password_reset_confirm,{"post_reset_redirect":"BeginningDash:password_reset_complete","template_name":"Beginning/reset_password_confirm.html"}, name='password_reset_confirm' ),
	url(r'^reset-password/complete/$', password_reset_complete,{"template_name":"Beginning/reset_password_complete.html"},name="password_reset_complete")
]

DashNig/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from BeginningDash import urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('BeginningDash.urls', namespace="BeginningDash")),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/newpartials/about.html
{% load static %}
<!-- about -->
<style type="text/css">
	img.zoom-img:hover{
		border-radius: 5px;
	}
</style>
<div class="about-w3layouts">

	<div class="container">
		<div class="hidden-xs ">
			<div class="col-md-6 col-sm-6 gallery-grids agileits w3layouts gallery-grids1 wow slideInLeft">
				<div class="gallery-grid-images agileits w3layouts">
					<div class="col-md-4 col-sm-4 gallery-grid gallery-grid-1 history-grid-image">
						<img src=" {% static 'contactpage/images/bitimage.jpg' %}" alt="bitimage" class="zoom-img">
					</div>
					<div class="col-md-4 col-sm-4 gallery-grid gallery-grid-2 history-grid-image">
						<img src=" {% static 'contactpage/images/chartimage.jpg' %}" alt="chartimage" class="zoom-img">
					</div>
					<div class="col-md-4 col-sm-4 gallery-grid gallery-grid-3 history-grid-image">
						<img src=" {% static 'contactpage/images/itelimage.jpg' %}" alt="itelimage" class="zoom-img">
					</div>

					<div class="col-md-4 col-sm-4 gallery-grid gallery-grid-4 history-grid-image">
						<img src=" {% static 'contactpage/images/analysis.jpg' %}" alt="analysis" class="zoom-img">
					</div>
					<div class="col-md-4 col-sm-4 gallery-grid gallery-grid-5 history-grid-image">
						<img src=" {% static 'contactpage/images/litimage.jpg' %}" alt="litimage" class="zoom-img">
					</div>
					<div class="col-md-4 col-sm-4 gallery-grid gallery-grid-6 history-grid-image">
						<img src=" {% static 'contactpage/images/dashimage.jpg' %}" alt="dashimage" class="zoom-img">
					</div>
					<div class="clearfix"></div>
				</div>
			</div>
		</div>
		<div class="hidden-lg hidden-md hidden-sm">
			<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
    <!-- #i dont want indicators -->

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
  <style type="text/css">
  	#myborder{
  		border-radius: 5px;
  		border-color: black;
  		border-width:4px;
  		border-style: solid;
  	}
  </style>
    <div class="item active">
    <div>
		<img src=" {% static 'contactpage/images/chartimage.jpg' %}" alt="chartimage" class="zoom-img" id="myborder">
		</div>    
    </div>
    <div class="item">
		<div>
	    <img src=" {% static 'contactpage/images/bitimage.jpg' %}" alt="bitimage" class="zoom-img" id="myborder">
	   </div> 
    </div>
    <div class="item">
		<div>
	   <img src=" {% static 'contactpage/images/itelimage.jpg' %}" alt="itelimage" class="zoom-img" id="myborder">
	   </div> 
    </div>
    <div class="item">
		<div>
	    <img src=" {% static 'contactpage/images/analysis.jpg' %}" alt="analysis" class="zoom-img" id="myborder">
	   </div> 
    </div>
    <div class="item">
		<div>
	    <img src=" {% static 'contactpage/images/litimage.jpg' %}" alt="litimage" class="zoom-img" id="myborder">
	   </div> 
    </div>
     <div class="item">
		<div>
	    <img src=" {% static 'contactpage/images/dashimage.jpg' %}" alt="dashimage" class="zoom-img" id="myborder">
	   </div> 
    </div>
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
		</div>

		<div class="col-md-6 col-sm-6 gallery-grids agileits w3layouts gallery-grids2 wow slideInRight">
			<h2 class="tittle-agileits-w3layouts">About <span style="color: gold;">DASHNG super</span> </h2>
			<h5><i class="fa fa-th-large" aria-hidden="true"></i>&nbsp;WHO WE ARE&nbsp; <i class="fa fa-usb" aria-hidden="true"></i>&nbsp;WHAT WE DO</h5>
			<p class="para-w3-agile">	DashNG Super is a simple web application that alows users store their files in a clean manner. These files are saved in the cloud and are easily retrieved by the user when needed.
			</p>
			<a href="{% url 'BeginningDash:aboutfornonuser' %}" class="button-w3layouts hvr-rectangle-out">know more</a>
		</div>
		<div class="clearfix"></div>

	</div>
</div>
	<!-- //about -->

templates/newpartials/banner.html
<!-- banner -->
  {% load static %}
  {% url "BeginningDash:loginX_regX" as loginX_regX %}  
  {% url "BeginningDash:contact" as contact %} 
  {% url "BeginningDash:aboutus" as aboutus %} 
  {% url "BeginningDash:aboutfornonuser" as aboutfornonuser %} 

<div class="banner" id="home">
  <div class="banner-overlay-agileinfo">
  <div class="top-header-agile">
    <h1><a class="col-md-4 navbar-brand" href="{% url 'BeginningDash:home' %}">DashNG<span>We Save Your Files For The Future</span></a></h1>
    <div class="col-md-4 top-header-agile-right">
        
      </div>
      <div class="col-md-4 top-header-agile-left">
        <ul class="num-w3ls">
          <li><i class="fa fa-phone" aria-hidden="true"></i></li>
          <li>+2349062360533</li>
        </ul>
        <div class="w3ls_search">
                          <div class="cd-main-header">
                            <ul class="cd-header-buttons">
                              <li><a class="cd-search-trigger" href="#cd-search"> <span></span></a></li>
                            </ul> <!-- cd-header-buttons -->
                          </div>
                        <div id="cd-search" class="cd-search">
                        <div class="hidden-xs hidden-sm"><h5 style="color: whitesmoke; font-weight: bold;"><i class="fa fa-upload" aria-hidden="true"></i>&nbsp;DashNGSuper all data-safe platform [Upgrade Coming Soon!]</h5></div>
                        <div class="hidden-md hidden-lg"><h5 style="color: whitesmoke; font-weight: bold;"><i class="fa fa-upload" aria-hidden="true"></i>&nbsp;[Upgrade Coming Soon!].</h5></div>
                        </div>
                        </div>
          </div>
      
      <div class="clearfix"></div>
    </div>

    <div class="container">
      <nav class="navbar navbar-default">
        <div class="navbar-header navbar-left">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse navbar-right" id="bs-example-navbar-collapse-1">
 
          <nav class="link-effect-3" id="link-effect-3">
            <ul class="nav navbar-nav">
              <li {% if request.path == loginX_regX %} class="active" {% endif %}><a href="{% url 'BeginningDash:loginX_regX' %}" data-hover="Home">Home</a></li>
              <li  {% if request.path == aboutfornonuser %} class="active" {% endif %}><a href="{% url 'BeginningDash:aboutfornonuser' %}"><span class="glyphicon glyphicon-globe"></span> About Us</a></li>      
              <li {% if request.path == mycontact4offlineuser %} class="active" {% endif %}><a href="{% url 'BeginningDash:mycontact4offlineuser' %}" data-hover="Contact Us">Contact Us</a></li>
              
            </ul>
          </nav>
    
         
    
        </div>
      </nav>  
      <div class="w3l_banner_info">
        <section class="slider">
          <div class="flexslider">
            <ul class="slides">
              <li>
                <div class="wthree_banner_info_grid">
                  <h3><span>HiTech</span>Welcome to <br>DashNG~VS</h3>
                  <p>We save your files for the future</p>
                </div>
              </li>
              <li>
                <div class="wthree_banner_info_grid">
                  <h3><span>Cloud</span>Files<br>Securely stored</h3>
                  <p>Stores Automatically In Our Cloud Database</p>
                </div>
              </li>
              <li>
                <div class="wthree_banner_info_grid" style="color: black;">
                  <h3><span>CSRF</span>Featuring the  <br>Latest Build Of </h3>
                  <p>Tight Web-Security!</p>
                </div>
              </li>
              <li>
                <div class="wthree_banner_info_grid">
                  <h3><span>Access</span>Ready To Use <br>With Your Files</h3>
                  <p>Easily Uploadable And Downloadable At Ease!</p>
                </div>
              </li>
            </ul>
          </div>
        </section>
            
      </div>      
    </div>
  </div>
</div>
<!-- //banner --> 

templates/newpartials/banner2.html
<!-- banner -->
  {% load static %}
  {% url "BeginningDash:begin" as begin %} 
  {% url "BeginningDash:home" as home %} 
  {% url "BeginningDash:view_profile" as viewprofile %} 
  {% url "BeginningDash:logout" as logout %} 
  {% url "BeginningDash:signup" as signup %} 
  {% url "BeginningDash:code" as code %} 
  {% url "BeginningDash:aboutfornonuser" as aboutfornonuser %} 
  {% url "BeginningDash:mycontact4offlineuser" as mycontact4offlineuser %} 
  {% url "BeginningDash:view_profile" as view_profile %} 
  {% url "BeginningDash:edit_profile" as edit_profile %} 
  {% url "BeginningDash:aboutus" as aboutus %} 
  {% url "BeginningDash:code_files" as code_files %} 
  {% url "BeginningDash:allfiles" as file_files %} 
  {% url "BeginningDash:gallery" as gallery %} 
  {% url "BeginningDash:contact" as contact %} 
  {% url "BeginningDash:allfiles" as allfiles %} 
  {% url "BeginningDash:allcodes" as allcodes %} 
  {% url "BeginningDash:created_document" as created_document %}
<div class="banner inner-banner-w3-agileits" id="home">
	<div class="banner-overlay-agileinfo">
		<div class="top-header-agile">
			<h1><a class="col-md-4 navbar-brand" href="{% url 'BeginningDash:home' %}">DashNG<span>We Save Your Files For The Future</span></a></h1>
			<div class="col-md-4 top-header-agile-right">
				
			</div>
			<div class="col-md-4 top-header-agile-left">
				<ul class="num-w3ls">
					<li><i class="fa fa-phone" aria-hidden="true"></i></li>
					 <li>+2349062360533</li>
				</ul>
				<div class="w3ls_search">
					<div class="cd-main-header">
						<ul class="cd-header-buttons">
							<li><a class="cd-search-trigger" href="#cd-search"> <span></span></a></li>
						</ul> <!-- cd-header-buttons -->
					</div>
					<div id="cd-search" class="cd-search">
						<div class="hidden-xs hidden-sm"><h5 style="color: whitesmoke; font-weight: bold;"><i class="fa fa-upload" aria-hidden="true"></i>&nbsp;DashNGSuper all data-safe platform [Upgrade Coming Soon!]</h5></div>
						<div class="hidden-md hidden-lg"><h5 style="color: whitesmoke; font-weight: bold;"><i class="fa fa-upload" aria-hidden="true"></i>&nbsp;[Upgrade Coming Soon!].</h5></div>
					</div>
				</div>
			</div>
			
			<div class="clearfix"></div>
		</div>

		<div class="container">
			<nav class="navbar navbar-default">
				<div class="navbar-header navbar-left">
					<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
				</div>
				<!-- Collect the nav links, forms, and other content for toggling -->
				<div class="collapse navbar-collapse navbar-right" id="bs-example-navbar-collapse-1">
					
					<nav class="link-effect-3" id="link-effect-3">
            <ul class="nav navbar-nav">
              <li {% if request.path == home %} class="active" {% endif %} ><a href="{% url 'BeginningDash:home' %}" data-hover="Home"><i class="fa fa-home" aria-hidden="true"></i>&nbsp;Home</a></li>
              <li class="dropdown menu__item">
                <a href="#" class="dropdown-toggle menu__link"  data-toggle="dropdown" data-hover="Pages" role="button" aria-haspopup="true" aria-expanded="false">DashNG~VS<span class="caret"></span></a>
                <ul class="dropdown-menu">
                {% if request.user.is_authenticated %}
                  <li  {% if request.path == aboutus %} class="active" {% endif %}><a href="{% url 'BeginningDash:aboutus' %}"><span class="glyphicon glyphicon-globe"></span> About Us</a></li>

                {% else %}
                 <li  {% if request.path == aboutfornonuser %} class="active" {% endif %}><a href="{% url 'BeginningDash:aboutfornonuser' %}"><span class="glyphicon glyphicon-globe"></span> About Us</a></li>

                {% endif %}
                 {% if request.user.is_authenticated %}
                  <li  {% if request.path == contact %} class="active" {% endif %}><a href="{% url 'BeginningDash:contact' %}" data-hover=""><i class="fa fa-map-marker" aria-hidden="true"></i>&nbsp;Contact Us</a></li>
                 {% else %}
                 <li  {% if request.path == mycontact4offlineuser %} class="active" {% endif %}><a href="{% url 'BeginningDash:mycontact4offlineuser' %}" data-hover=""><i class="fa fa-map-marker" aria-hidden="true"></i>&nbsp;Contact Us</a></li>
                 {% endif %}
                
                
                 
                </ul>
              </li>
             {% if request.user.is_authenticated %}
              <li {% if request.path == gallery %} class="active" {% endif %} ><a href="{% url 'BeginningDash:gallery' %}" data-hover="Gallery"><span class="glyphicon glyphicon-picture"></span> Gallery</a></li>
              <li class="dropdown menu__item">
                <a href="#" class="dropdown-toggle menu__link"  data-toggle="dropdown" data-hover="Pages" role="button" aria-haspopup="true" aria-expanded="false"><i class="fa fa-upload" aria-hidden="true"></i>&nbsp;Uploads<span class="caret"></span></a>
                <ul class="dropdown-menu">
                <li  {% if request.path == view_profile %} class="active" {% endif %} ><a href="{% url 'BeginningDash:view_profile' %}"><i class="fa fa-user-circle-o" aria-hidden="true"></i>&nbsp;My Profile</a></li>
                  <li  {% if request.path == allfiles %} class="active" {% endif %}><a href="{% url 'BeginningDash:allfiles' %}"><span class="glyphicon glyphicon-cloud-upload"></span> Files Uploaded</a></li>
                  <li {% if request.path == allcodes %} class="active" {% endif %}><a href="{% url 'BeginningDash:allcodes' %}"><i class="fa fa-code" aria-hidden="true"></i>&nbsp;Code Uploaded</a></li>
                  
                 
                </ul>
              </li>
              <li {% if request.path == code %} class="active" {% endif %} ><a href="{% url 'BeginningDash:code' %}" data-hover="Codes"><i class="fa fa-code" aria-hidden="true"></i>&nbsp;Codes</a></li>
              
              <li><a href="{% url 'BeginningDash:logout' %}" data-hover="Log-out">Log-out&nbsp;<span class="glyphicon glyphicon-log-out"></span></a></li>
              {% else %}
               <li><a href="{% url 'BeginningDash:home' %}" data-hover="Log-out">Log-In&nbsp;<span class="glyphicon glyphicon-log-out"></span></a></li>
              {% endif %}
            </ul>
          </nav>
				</div>
			</nav>	
			{% if request.path == home %} 
			<h2 class="inner-tittle-w3layouts" >Home</h2>
			{% elif request.path == code %}
			<h2 class="inner-tittle-w3layouts" >Code</h2>
			{% elif request.path == gallery %}
			<h2 class="inner-tittle-w3layouts" >Gallery</h2>
			{% elif request.path == aboutus %}
			<h2 class="inner-tittle-w3layouts" >About Us</h2>
			{% elif request.path == allfiles %}
			<h2 class="inner-tittle-w3layouts" >Uploaded Files</h2>
			{% elif request.path == allcodes %}
			<h2 class="inner-tittle-w3layouts" >Uploaded Codes</h2>
			{% elif request.path == gallery %} 
			<h2 class="inner-tittle-w3layouts" >Gallery</h2>
			{% elif request.path == view_profile %}
			<h2 class="inner-tittle-w3layouts" >Profile [**{{ user }}**]</h2>
			{% elif request.path == edit_profile %}
			<h2 class="inner-tittle-w3layouts" >Profile Edit Form</h2>
			{% endif %} 
		</div>
	</div>
</div>
<!-- //banner -->

templates/newpartials/footer.html
<!--footer-->
<div class="footer w3layouts">
  <div class="container">
    <div class="footer-row w3layouts-agile">
      <div class="col-md-4 footer-grids w3l-agileits">
        <h6><a href="index.html">DashNG~VS</a></h6>
        <p class="footer-one-w3ls">Our primary agenda is secure your files for the future. You can get in touch with us anytime via our social media platforms. </p>
        <div class="top-header-agile-right">
          
        </div>
        <div class="clearfix"></div>
      </div>
      <div class="col-md-2 footer-grids w3l-agileits">
        <h3><span class="glyphicon glyphicon-th-large" style="color: orange; font-size: 18px;"></span>&nbsp;Content</h3>          
        <ul class="b-nav">
        <!-- #i think i will use javascript here
        Failed  attempt ... null  -->
        <!--   Trying another initiated -->

        <li><a href="{% url 'BeginningDash:home' %}"><i class="fa fa-home" aria-hidden="true"></i>&nbsp;Home</a></li>
        {% if request.user.is_authenticated %}
        <li  {% if request.path == aboutus %} class="active" {% endif %}><a href="{% url 'BeginningDash:aboutus' %}"><span class="glyphicon glyphicon-globe"></span> About Us and Sponsoring</a></li>

        {% else %}
        <li  {% if request.path == aboutfornonuser %} class="active" {% endif %}><a href="{% url 'BeginningDash:aboutfornonuser' %}"><span class="glyphicon glyphicon-globe"></span> About Us and Sponsoring</a></li>

        {% endif %}
        {% if request.user.is_authenticated %}
        <li  {% if request.path == contact %} class="active" {% endif %}><a href="{% url 'BeginningDash:contact' %}" data-hover=""><i class="fa fa-map-marker" aria-hidden="true"></i>&nbsp;Contact Us</a></li>
        {% else %}
        <li  {% if request.path == mycontact4offlineuser %} class="active" {% endif %}><a href="{% url 'BeginningDash:mycontact4offlineuser' %}" data-hover=""><i class="fa fa-map-marker" aria-hidden="true"></i>&nbsp;Contact Us</a></li>
        {% endif %}

      </ul>
    </div>
    <div class="col-md-3 footer-grids w3l-agileits">
      <h3><span class="glyphicon glyphicon-bullhorn" style="color:orange; font-size: 18px;"></span>&nbsp;Contact Info</h3>
      <p>+2349062360533</p>
      <p><a href="dashngsuper@gmail.com">support@dashngsuper.com</a></p>
 
    </div>
    <div class="clearfix"> </div>
  </div>
</div>
</div>
<!--//footer--> 

templates/newpartials/regsuccess.html
{% extends 'base.html' %}
{% block content %}
<br>
{% if messages %}
{% for message in messages %}
<div class="alert alert-success alert-dismissible" role="alert" align="middle">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  <strong><i class="fa fa-registered" aria-hidden="true"></i>&nbsp;{{message}}</strong>
</div>
<hr>
<div class="well well-sm" align="middle"><i class="fa fa-check-square-o" aria-hidden="true"></i>&nbsp;Click <a href="{% url 'BeginningDash:home' %}"> Here </a> to sign in </div>
<hr>
{% endfor %}
{% endif %}



{% endblock content %}

templates/newpartials/services.html
{% load static %}
<!--/services-->
<div class="services-w3-agileits w3agileits-ref">
  <div class="col-md-6 services-left">
    <div class="service-grid1">
      <div class="col-md-4 service-grids-w3ls">
        <i class="fa fa-language" aria-hidden="true"></i>
        <h5>Language Translation</h5>
        <p>DashNGSuper is officially written in English, however, our pages can be translated to lots of local and foreign languages. </p>
      </div>
      <div class="col-md-4 service-grids-w3ls">
        <i class="fa fa-users" aria-hidden="true"></i>
        <h5>Large Base Users</h5>
        <p>Our users span across different continents.</p>
      </div>
      <div class="col-md-4 service-grids-w3ls">
        <i class="fa fa-life-ring" aria-hidden="true"></i>
        <h5>Premium Upgrade</h5>
        <p>We power upgrade to premium to allow users have unlimited access.</p>
      </div>
      <div class="clearfix"></div>
    </div>
    <div class="service-grid2">
      <div class="col-md-4 service-grids-w3ls">
        <i class="fa fa-database" aria-hidden="true"></i>
        <h5>Dynamic Database</h5>
        <p>We present not just tough but a dynamic database.</p>
      </div>
      <div class="col-md-4 service-grids-w3ls">
        <i class="fa fa-crosshairs" aria-hidden="true"></i>
        <h5>Traffic Regulations</h5>
        <p>Our unique traffic regulators provides a stable means for easy-accessibility of the site.</p>
      </div>
      <div class="col-md-4 service-grids-w3ls">
        <i class="fa fa-upload" aria-hidden="true"></i>
        <h5>Files Upload</h5>
        <p>A Free user enjoy the total upload of 1GB(Gigabyte;) and premium users enjoy more.</p>
      </div>
      <div class="clearfix"></div>
    </div>    
  </div>
  <div class="col-md-6  services-right">
    <div class="services-info">
      <h3 class="tittle-agileits-w3layouts white-w3ls">Who We Sponsor</h3>
      <p class="para-w3-agile white-w3ls">
        Have you ever thought of making money online ??<br>
        voilà !! you have come to the right place.<br>
        We give you a means to make and invest in wealth for yourself for free.<br>
        Care to know more?? 
      </p>
      <a href="{% url 'BeginningDash:aboutfornonuser'  %}" class="button-w3layouts hvr-rectangle-out">Learn more</a>
    </div>
  </div>
  <div class="clearfix"></div>
</div>
<!--//services-->

<!-- background-size: cover;-webkit-background-size: cover;-moz-background-size: cover;-o-background-size: cover;-ms-background-size: cover;padding: 5em 7em; -->

templates/newpartials/testimonials.html
{% load static %}
<!-- agile_testimonials -->
<div class="test">
  <div class="container">
    <div class="col-md-3 test-left-agileinfo">
      <h3 class="tittle-agileits-w3layouts">Testimonials</h3>
    </div>
    <div class="col-md-9 test-gr">
      <div class=" test-gri1">
       <div id="owl-demo2" class="owl-carousel">
        {% for items in peoples_view %}
        <div class="agile">
          <div class="test-grid">
            <div class="col-md-8 test-grid1">
              <p class="para-w3-agile">{{items.Comment}}</p>
              <h4>{{items.Name}}</h4>
              <span>{{items.Occupation}}</span>
            </div>  
            <div class="col-md-4 test-grid2">
              <img src="{{ items.Photo.url }}" alt="" class="img-r">
            </div>
          </div>  
          <div class="clearfix"></div>
        </div>
        {% endfor %}
      </div>
    </div>  
  </div>
</div>
</div>
<!-- //agile_testimonials -->